### ISSUE TITLE
Attribute `name` is been rendered as `data-name`

### ISSUE THREAD

**Issue by mateuspv** [uploadcare/react-widget#100]
The documentation mention the ability to define the `name` attribute, however, it's been transformed into `data-name`.

**Version**:  `"@uploadcare/react-widget": "^1.2.1"`

**Example**:

```js
<Widget
              publicKey="Secret"
              id="file"
              name="file"
              tabs="file url"
              previewStep="true"
            />
```

Result:
![Screen Shot 2020-01-08 at 17 05 20](https://user-images.githubusercontent.com/4995440/72011706-27c57c80-3239-11ea-8411-b0439ba37a09.png)

**Comment by jeetiss** [comment]
Thanks for issue!

> The documentation mention the ability to define the name attribute

Yep, we have that stuff in react guide, I will fix
