### ISSUE TITLE
Image preview not working for local files

### ISSUE THREAD

**Issue by heymartinadams** [uploadcare/react-widget#103]
## Error

![Screen Recording 2020-01-10 at 1 52 02 PM](https://user-images.githubusercontent.com/11673745/72189223-2dde6900-33b1-11ea-93bd-a44688e2ae39.gif)

It appears the image preview doesn’t work for me on the React Widget when uploading an image (getting an image file from the web works just fine). Image has proper size, is proper type, etc.

Using the widget in a local dev environment (`localhost:8080`). Any thoughts why this might be?

Unfortunately there’s no error message in the browser console.

#### Main.js
```js
import { useRef } from 'preact/hooks'
import Widget from '~/Widget'

export default () => {
  const widgetApi = useRef()
  return (
    <div>
      ...
      <Widget widgetApi={widgetApi} />
      ...
    </div>
  )
}
```

#### Widget.js
```js
import { createGlobalStyle } from 'styled-components'
import { Widget } from '@uploadcare/react-widget'

export default ({ widgetApi }) => {
  // hide widget
  const WidgetButtonStyle = createGlobalStyle`
    .uploadcare--widget__button,
    .uploadcare--widget__dragndrop-area,
    .uploadcare--progress,
    .uploadcare--widget__text {
      display: none;
    }`

  return (
    <div>
      <WidgetButtonStyle />
      <Widget
        ref={widgetApi}
        effects='crop,rotate,mirror,flip,enhance,sharp,blur'
        imagesOnly={true}
        onFileSelect={file => {
          console.log('File changed: ', file)
          if (file) {
            file.progress(info => console.log('File progress: ', info.progress))
            file.done(info => console.log('File uploaded: ', info))
          }
        }}
        onChange={info => console.log('Upload completed:', info)}
        previewStep={true}
        publicKey={process.env.PREACT_APP_UPLOADCARE}
        tabs='file url facebook gphotos dropbox instagram'
      />
    </div>
  )
}
```

**Comment by jeetiss** [comment]
You using `preact` with `react-widget`! wow!
I think you first on this way, congrats ⚡️

> Any thoughts why this might be?

Seems like `validators` integration works wrong, I am going to test it, but I afraid that it is broken because of preact.

**Comment by heymartinadams** [comment]
Thanks, @jeetiss. Any workaround — even if it’s a temporary hack (such as replacing code in `node_modules` 😬 (don’t tell anyone) — would be awesome. Def. prefer uploadcare over some of the other image platforms out there.

**Comment by heymartinadams** [comment]
When I restarted the project today, it somehow accepted the local file uploads — completely unsure why.

It still displays the `preview` pane (with error message) on `openDialog()`, so I’m doing a basic workaround with:
```js
const dialog = widgetApi.current.openDialog()
dialog.switchTab('file')
```

**Comment by jeetiss** [comment]
Hello @heymartinadams, I tried reproduce you problem but with react all works nice. First class support of preact will be grate, but we don't have resources for it yet

I think you can add empty `validator` as workaround and maybe that helps, like that

```jsx
const validators = [() => {}]

// ...

<Widget
  validators={validators}
  // other props 
/>
```
