### ISSUE TITLE
Can not set "preload" prop to null in TypeScript.

### ISSUE THREAD

**Issue by tthygesen** [uploadcare/react-widget#112]
I am using the React widget with Typescript and I can not set the "preload" prop to null since it's types are an component or undefined but undefined does not remove the default preloader. 

NPM: 
React : 16.11.0
TypeScript: 3.7.2
@uploadcare/react-widget: 1.2.2

The Error :
`Type 'null' is not assignable to type 'ComponentClass<{}, any> | FunctionComponent<{}> | undefined'`

Image of my widget:
![react widget](https://user-images.githubusercontent.com/33449127/72509669-4e427380-3848-11ea-8cb9-3656f2d3b59f.png)

**Comment by jeetiss** [comment]
Hello again @tthygesen 🙂
Nice catch!
Big thanks for issue, we will fix it
