### ISSUE TITLE
Question: Remove uploaded image

### ISSUE THREAD

**Issue by mateuspv** [uploadcare/react-widget#130]
Hi, this may be a question for uploadcare and not `react-widget` itself:

There's any way of implementing a `delete` button ?
![Screen Shot 2020-01-31 at 12 28 41](https://user-images.githubusercontent.com/4995440/73551540-547a4780-4425-11ea-9241-d72bcf7f48fc.png)

(Or uploadcare just handle the upload and I manually should remove files from the admin.)

Thanks

**Comment by optlsnd** [comment]
Hi @mateuspv, thank you for the question! The widget is just a client of Uploadcare upload API, and it can upload files only. It doesn't offer any functionality for deleting or modifying files. Deleting files from the widget could be also a security issue. If the widget could delete files, an attacker would be able to preload a file from your project with JS by a known UUID and delete it from your storage. You can manage your files via the UI of the [dashboard](https://uploadcare.com/dashboard/) or [REST API](https://uploadcare.com/docs/api_reference/rest/accessing_files/). Note that requests to REST API require authentication, so we strongly advise against making such requests directly from the front-end to prevent your secret key or secure signature from being exposed.
