### ISSUE TITLE
Error importing english-only version

### ISSUE THREAD

**Issue by mateuspv** [uploadcare/react-widget#153]
### Describe the bug

Hi, I'm having an issue importing the english-only version: `Widget not found via ... import/named`

```
webpack | 100%
lint    |
lint    | /app/_js/product/customizer/components/button-uploadcare/index.js
lint    |   14:10  error  Widget not found via ../../../../../node_modules/@uploadcare/react-widget/en/index.js -> ../../../../../node_modules/@uploadcare/react-widget/en/index-34867c89.js  import/named
lint    |
lint    | ✖ 1 problem (1 error, 0 warnings)
lint    |
```

This seems more a webpack/typescript issue rather than the library, but let me know if make sense for you.

### Environment

 - Library version:
```json
{
"uploadcare-widget": "3.8.3",
"@uploadcare/react-widget": "1.2.5"
}
```
 - Language/framework version: Linux (Docker)

**Comment by jeetiss** [comment]
Hello @mateuspv

Do you use `@uploadcare/react-widget` on server with node and Docker?
If that true, you will need run `@babel/plugin-syntax-dynamic-import` for node.
This should help.

Default version works because it have both formats (`cjs` and `esm`) and `en` version have only `esm` and use dynamic `import` that not supported in node yet.

**Comment by jeetiss** [comment]
Which version of webpack you use?

I think that this main fail reason: 
> Default version works because it have both formats (cjs and esm) and en version have only esm and use dynamic import that not supported in node yet.

But I don't have any suggestion why it not works

**Comment by mateuspv** [comment]
@jeetiss  I'm using uploadcare Widget on the frontend, no server side rendering.

```json
"webpack": "4.42.0",
"webpack-cli": "3.3.11",
"terser-webpack-plugin": "2.3.5"
```

Here is my babel config:
```js
module.exports = {
  comments: true,
  sourceType: 'module',
  presets: [
    [
      '@babel/preset-env',
      {
        modules: 'commonjs',
        useBuiltIns: false
      }
    ],
    ['@babel/preset-react']
  ],
  plugins: [
    [
      '@babel/plugin-transform-runtime',
      {
        helpers: true,
        regenerator: true
      }
    ]
  ]
}
```

I even tried `@babel/plugin-transform-modules-commonjs` but didn't worked.

**Comment by jeetiss** [comment]
Hello @mateuspv
I fixed this issue, feel free to upgrade
