### ISSUE TITLE
Custom Tab in React

### ISSUE THREAD

**Issue by guillaumegaluz** [uploadcare/react-widget#17]
Is there any example out there of custom tabs in React?
I created a [ticket](https://uploadcare.com/community/t/adding-a-custom-tab-in-react/1037) in the UC Community, if it's better to chat there! And there's a link to a working codepen with UC + React https://codepen.io/guillaumegaluz/pen/bPPMdr?editors=1011

Would appreciate some help, ideally an code example of someone who's done that before. 
Thanks!

**Comment by jeetiss** [comment]
Hello! I publish react-widget component today 🚀
We used it in our docs with gatsby

And mister @nd0ut wrote new custom tab example for you https://codesandbox.io/s/frosty-blackwell-do8cq

if you have any problems with [@uploadcare/react-widget](https://github.com/uploadcare/uploadcare-widget-react-demo/tree/react-widget) feel free to open new issues in this repo
