### ISSUE TITLE
onChange not called when the widget was emptied.

### ISSUE THREAD

**Issue by ferdinandgoor** [uploadcare/react-widget#171]
### Question

Hello everybody,

Im using the react widget on our App, and i'm using it in a component that displays the images uploaded in uploadcare.

Our component rely on the onChange callback to update it's state everytime there's a change in the widget.

Everything works fine until there's no more image in the widget then the onChange callback is not called so we can't update our component state.

I would like to know if it's a missing feature, a bug, if there's a workaround or if it was made like that on purpose.

IMO the onChange should be called everytime even if the widget is emptied by the user.

**Comment by jdrzewinski** [comment]
@ferdinandgoor got same issue here, did you find a way to handle it ?
