### ISSUE TITLE
Camera Tab Doesn't Upload On IOS an Doesn't Show Camera on MacOS

### ISSUE THREAD

**Issue by TransmissionsDev** [uploadcare/react-widget#196]
### Describe the bug

On IOS the camera tab will let you open your camera and take a photo but will say "Can't Upload" when you select the photo. It will also not let you upload a photo that you took from the camera app.

On MacOS the camera will not show at all and will just show a "Mirror" button.

On MacOS go to: https://codesandbox.io/s/7xpqp and open the camera tab. You will see this:
![ScreenShot-](https://user-images.githubusercontent.com/26209401/90103832-06a99a80-dcf8-11ea-957a-dcd0efe95ccc.png)

On IOS, try using the camera tab and take a photo. Tap the shutter button and try to let the photo upload. It will show "can't upload".

On IOS also try using the file upload tab and upload a photo you took with camera app. It will also show "can't upload".

### Expected behavior

The camera tab should upload properly on IOS and should show the camera feed on MacOS

### Environment

 - Library version: 1.3.0
 - Language/framework version: React 16.13.1
 - OS version: MacOS 10.15.4 and IOS 13.5

**Comment by jeetiss** [comment]
@TransmissionsDev thanks for issue report

Do you use safari? I can't reproduce the bug. Can you share more information about your environment?

**Comment by jeetiss** [comment]
I still can't reproduce the bug because all my friends update phones to fresh ios. I found bug in safari that looks similar 
https://bugs.webkit.org/show_bug.cgi?id=206219
Are you setup PWA in your app?

**Comment by TransmissionsDev** [comment]
Yep we are setup as a PWA.

Maybe try using my site at: https://spotbook.now.sh to see if you can reproduce.

(To use just click anywhere on the map and a modal will popup letting you upload an image)

**Comment by TransmissionsDev** [comment]
Thank you so much for that PR! The issue with uploading images on IOS was that photos were too large for the free plan! 

However, I still cannot take photos on Macos 10.15.4. on chrome 84.0.4147.135.
![ScreenShot-](https://user-images.githubusercontent.com/26209401/91594951-944fd180-e917-11ea-9425-04816c0f9d0f.png)

I've narrowed down the issue though. It works perfectly fine on Safari, and thats because Safari will allow the site to select my built in Facetime Camera. However on chrome, it selects a non default camera called "snap camera" which I must have installed a while ago. Even when I change the default camera and clear the site permissions to get the uploadcare widget to use the default camera, I still get the "snap camera".

This stackoverflow thread seems to indicate that for sites that request a high camera resolution and one is not available, it will use the non default: https://stackoverflow.com/questions/53021367/cant-choose-right-webcam-in-google-chrome/53021740

I don't have this issue when using something like https://www.cam-recorder.com/ so this does seem like some issue with Uploadcare.

If you have any more questions, feel free to follow up 👍
