### ISSUE TITLE
Wrong `onFileSelect` typings and readme info

### ISSUE THREAD

**Issue by LXSMNSYC** [uploadcare/react-widget#201]
In the [File Uploader API doc](https://uploadcare.com/docs/file_uploader_api/widget/#widget-on-upload-complete), the `file` you receive in the `onChange` event has the methods `progress` and `done`, in contrast, the `onChange` of the React widget only gives you the `FileInfo` interface but without the `progress` and `done`. Is there a way to access these? It would be useful for presenting the progress or loading UI whenever an upload is being processed.

**Comment by jeetiss** [comment]
@LXSMNSYC I opened PR with fix. Can you review and approve that everything is okey?
