### ISSUE TITLE
Minor issue with types not declaring crop property

### ISSUE THREAD

**Issue by davedbase** [uploadcare/react-widget#225]
I added an onChange property to the widget, uploaded an asset successfully and console logged the returned info property. All the values are there however my linter warned me that the FileInfo type is missing the crop property: https://github.com/uploadcare/react-widget/blob/28fcc090af7cf316967cbdbe737e5eda1afab8a4/types/index.d.ts#L233-L246
Seems like crop contained height, width, left, top.

**Comment by jeetiss** [comment]
@davedbase you right! Thanks for report
I fixed types definition
