### ISSUE TITLE
Support for React 17?

### ISSUE THREAD

**Issue by ObserverMoment** [uploadcare/react-widget#240]
### Library seems to not support React 17?

I am trying to install the UploadCare react library via NPM and am getting the following error thrown. I am using React 17.0.1.

> npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from @uploadcare/client-suspense@1.0.2
npm ERR! node_modules/@uploadcare/react-widget/node_modules/@uploadcare/client-suspense
npm ERR!   @uploadcare/client-suspense@"^1.0.2" from @uploadcare/react-widget@1.3.4
npm ERR!   node_modules/@uploadcare/react-widget
npm ERR!     @uploadcare/react-widget@"*" from the root project

**Comment by nd0ut** [comment]
Hey @ObserverMoment

Thanks for report. It was fixed in `v1.3.5`, check it out.
