### ISSUE TITLE
No Such Tab: drive

### ISSUE THREAD

**Issue by ObserverMoment** [uploadcare/react-widget#241]
### Adding Google Drive option to tabs prop to React Widget throws error

According to the docs here:

[https://uploadcare.com/docs/uploads/file-uploader/?utm_source=github&utm_campaign=uploadcare-widget#upload-source-list](url)

This should work

### Code / screenshots

> <Widget
    publicKey={process.env.NEXT_PUBLIC_UPLOADCARE_PUBLIC_KEY}
    onChange={onUploadComplete}
    tabs="file url dropbox drive"
    validators={
      allowedFileTypes
        ? [(fileInfo: FileInfo) => fileTypeCheck(fileInfo, allowedFileTypes)]
        : []
    }
  />

But it throws an error from here:

`value: function addTab(name) {
        var _this4 = this

        var TabCls, tabButton, tabIcon, tabPanel;

        if (name in this.tabs) {
          return;
        }

        TabCls = registeredTabs[name];

        if (!TabCls) {
          throw new Error("No such tab: ".concat(name));
        }`

<img width="971" alt="Screenshot 2021-02-22 at 11 14 23" src="https://user-images.githubusercontent.com/20599210/108701053-5ebf2600-74ff-11eb-81f1-9d51dbeedcd7.png">

### Environment

 - Library version: "@uploadcare/react-widget": "^1.3.4",
 - Language/framework version: "react": "^17.0.1",
    "react-dom": "^17.0.1",

Have I misunderstood the correct syntax?

Thanks,

Rich

**Comment by optlsnd** [comment]
Hi @ObserverMoment,

Sorry, it looks like we have a typo in our docs. The actual name of the Google Drive tab is `gdrive`. Changing the tab name should help. We'll fix the docs asap.

**Comment by ObserverMoment** [comment]
Yeah, that works, thanks
