### ISSUE TITLE
Panel 'value' prop not working

### ISSUE THREAD

**Issue by mattevans-dev** [uploadcare/react-widget#247]
Hi, I'm using the <Panel /> component in my code instead of the default <Widget />. All of the props work as expected apart from 'value'. I want to be able to pass through a default value in the form of an image uuid but I'm not sure if this is possible with the Panel component currently? It works with Widget but not Panel

Any help would be much appreciated
Thanks,
Matt

**Comment by nd0ut** [comment]
Hey @mattevans-dev 
Unfortunately, setting a default image in the react-widget panel is not supported yet, but this is on our roadmap. We plan to add this functionality later in Q2 2021

**Comment by nd0ut** [comment]
Hey @mattevans-dev! We have released v2.0.0 with an updated Panel component 🚀

**Comment by mattevans-dev** [comment]
Hey @nd0ut, that's great! Thanks for letting me know and adding in the feature 🎉
