### ISSUE TITLE
React-widget crashes after uploadcare-widget peer-dependency update

### ISSUE THREAD

**Issue by yoo-hooo** [uploadcare/react-widget#248]
### Describe the bug

Local build and pipelines fail to build after peer-dependency `uploadcare-widget`'s newest version (v3.10.3) was released.

### Expected behavior

Building not failing.

### Code / screenshots

<img width="839" alt="Schermafbeelding 2021-03-09 om 14 15 49" src="https://user-images.githubusercontent.com/8599398/110476405-3bd96800-80e2-11eb-9750-b31a3b598344.png">

Pinning `uploadcare-wiget` to v3.10.2 is a current workaround for this problem.

### Environment

 - Library version: v1.3.5 (latest)
 - Language/framework version: React (v16.14.0) - JavaScript
 - OS version: -

**Comment by nd0ut** [comment]
@yoo-hooo 
Sorry about that ridiculous mistake, we're fixed it at 3.10.4

**Comment by yoo-hooo** [comment]
@nd0ut Thanks for the quick fix 👍

**Comment by yoo-hooo** [comment]
@nd0ut Yeah, it's strange since everything seems fine. I'm using yarn in my project, basically what I've done is: deleted `yarn.lock` file, deleted local `node_modules`, deleted my container, reinstalled the `node_modules` and rebuild the container from scratch, but to no avail. I'll test once more this afternoon if I find some time. For now I can continue by pinning it to a previous version :)

**Comment by yoo-hooo** [comment]
@nd0ut Ok, I've tested building again with the latest version of `uploadcare-widget` and this time it succeeded building without crashing. No idea, what's changed but this ticket can be closed as far as I'm concerned 😄 
Thanks again for the quick fix!
