### ISSUE TITLE
How to source ucare-widget-chunk.js properly?

### ISSUE THREAD

**Issue by NichoCM** [uploadcare/react-widget#262]
### Question

Hey guys, I don't think this qualifies exactly as a bug so I'm going to post it as a question.

I noticed some errors implementing the react widget where my local environment didn't like downloading the source for `ucare-widget-chunk.js`, which is required for the app to function properly. The reason is pretty obvious, but I don't think this is the right way to approach loading that library in a node/React application. If possible, the library should be directly imported into the source of the react library (in my opinion). I was able to do this myself after installing the uploadcare-widget library and writing my own wrapper component.

To explain the issue I'm facing, I'll first describe our environment.

We have an SPA, meaning almost all routes on our server (with very explicit exceptions) redirect directly to the SPA source, where a router built into the application takes over rendering pages. It's a pretty common approach to SPA, so I don't see anything inherently wrong with this approach. This causes issues with the `ucare-widget-chunk.js`bundle since the server would treat that as another route to load the SPA. The simple solution (and likely what we'll do in the meantime) is to just add `ucare-widget-chunk.js` as an exception in our router, and load the source properly. This does work fine, but you can imagine if libraries had a tendency of making requests to fetch their components, we'd eventually have a huge mess of exceptions to include.

The other issue is directly with the development environment. In development, our code/assets are sourced from a `localhost` server, meaning it's not sourced from the same origin as the website. This is also pretty normal for our type of development environment. Since our server is hosted at (for example) `test.dev`, but our assets are loaded from `localhost`, there is no way for the widget to know where to load the correct `ucare-widget-chunk.js` from. To get around this, I had to create a route which redirects to the proper bundle file - which works but is quite hacky.

Of course if you see more appropriate workarounds to any of the issues above, please let me know! I do have a couple of solutions I can propose which may be more appropriate.

1. I think the best solution is to not make any http requests to access the source, but rather to have it included directly in the bundle. You may have reasons to not do it this way (e.g performance, or other technical reasons), so I understand if this was deliberate.

2. If bundling isn't an option, then perhaps Uploadcare can host a static version of the bundle that the libraries can request externally? I'm not a huge fan of relying on other servers for assets, but seeing as to use the uploader we need a connection to Uploadcare's servers anyway, this probably isn't a huge deal.

3. Failing both those options, perhaps a simple way to specify what endpoint the bundle should be loaded from? I saw this `scriptBase` prop, and I thought this was the way to achieve that but it wasn't working for me (didn't seem to make any impact).

More details about our environment:

 Widget package info: "@uploadcare/react-widget": "^1.2.0",
 Bundler: Webpack 4
 
 Let me know if you need any more info!

**Comment by nd0ut** [comment]
Hey @NichoCM

`react-widget` isn't downloading and evaluating `ucare-widget-chunk.js` directly, it uses [dynamic import syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) instead. The reason why we're using dynamic imports is simple - our widget is too big to be included in the client's application bundle by default. 

On the build stage, webpack processes this syntax and splits chunks according to it's configuration. That is, webpack decides  how many chunks to create and what url to load them from.

I can suggest two possible solutions:

1. Import commonjs version of `react-widget`. It uses static require instead of dynamic import, so your bundler won't create any chunks. 
   ```
   import { Widget } from "@uploadcare/react-widget/dist/cjs";
   ```

2. Configure webpack to disable code splitting. This can be achieved using [LimitChunkCountPlugin](https://webpack.js.org/plugins/limit-chunk-count-plugin/). Public chunks url is specified with `publicPath` option.
   ```
   output: {
      publicPath: 'http://localhost:8000/'
   },
   plugins: [
      new webpack.optimize.LimitChunkCountPlugin({
         maxChunks: 1,
      })
   ]
   ```

**Comment by elMatadito** [comment]
We have a similar case, IDK if it's a bug or a bad implementation on our side. 

The scenario is when the `service worker` is enabled, and the user visit the app after new deployment, the browser tries to serve the old version of the uploadcare chunk and it throw an exception (we catch with Sentry) 

The error: `Loading chunk 3 failed. (missing: https://example.com/static/js/ucare-widget-chunk.29a150a0.chunk.js)` 

We're using the @uploadcare/react-widget ^1.3.2

We will try the solution 1 that you suggested @nd0ut
