### ISSUE TITLE
Access to the fileFrom File Uploader API

### ISSUE THREAD

**Issue by keichan34** [uploadcare/react-widget#278]
### Brief description of the feature and motivation behind it

I'd like to access the [fileFrom File Uploader API](https://uploadcare.com/docs/file-uploader-api/files-uploads/#file-from-url) from React. Is there a reason why the whole File Uploader API isn't being exposed to React users?

My particular use case is a user chooses an image from another API that returns a list of image URLs -- I'd like to have the user upload one of these images to Uploadcare.

Alternatives include possibly creating a new custom tab that include the results from that API, but that would introduce extra clicks for the user.. I'd like to upload the file by default, if possible...

Currently, I'm using the [upload client](https://www.npmjs.com/package/@uploadcare/upload-client) to upload the file, then set the `value` of the uploader widget to the UUID of this file.

**Comment by optlsnd** [comment]
Hi @keichan34, thanks for the question! You can simply import `uploadcare` into your component

```js
import uploadcare from "uploadcare-widget";
```

Check out this [sandbox](https://codesandbox.io/s/uploadcare-react-widget-preload-file-from-url-gy2f7?file=/src/index.js) to see how it works.

**Comment by keichan34** [comment]
@optlsnd Thanks a lot for the demo, this looks like it would work.
