### ISSUE TITLE
Can not import @uploadcare/react-widget/en-min/

### ISSUE THREAD

**Issue by skreutzberger** [uploadcare/react-widget#331]
### Describe the bug

Neither via NPM nor via YARN can I import / add `@uploadcare/react-widget/en-min/` as described in the README.

### Expected behavior
The installation should work.

### Code / screenshots

`npm install @uploadcare/react-widget/en-min/` -> returns 
```
npm ERR! code ENOENT
npm ERR! syscall open
```

`yarn add @uploadcare/react-widget/en-min/` -> returns:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@uploadcare%2freact-widget/en-min/: 
Request \"https://registry.yarnpkg.com/@uploadcare%2freact-widget/en-min/\" returned a 405".
```

### Environment

 - Library version: 
 - Language/framework version: NPM 8.5.0, YARN 1.22.19
 - OS version:  macOS 12.3.1

**Comment by nd0ut** [comment]
Hey @skreutzberger,

you should install `@uploadcare/react-widget` but import `@uploadcare/react-widget/en-min`

**Comment by nd0ut** [comment]
Those bundles are available as ESM only. 

Next.js should support ESM modules by default.
I checked it on [StackBlitz](https://stackblitz.com/edit/nextjs-zevdrm?file=pages/index.js) and it works.

Which version of Next.js are you using?

**Comment by skreutzberger** [comment]
Hi, I am using Next.js 12.1. I also tried to directly import the `/dist/esm` folder but it did not work (but I also don't know what I am really doing  😅 since that whole NPM thing is new to me)

**Comment by nd0ut** [comment]
I was able to reproduce the problem, trying to solve. Thanks. Seems it's on the our side.

**Comment by nd0ut** [comment]
@skreutzberger 

Please update library to `v2.1.3` and import it by `@uploadcare/react-widget/en-min/index.js` path (trailing `/index.js` is important).

**Comment by skreutzberger** [comment]
Thanks for the quick fix! Unfortunately I now receive the following error:

```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/sebastian/xyz/node_modules/@uploadcare/react-widget/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

**Comment by heymartinadams** [comment]
For what it’s worth, I’m running into the same issue this morning:
```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/martinadams/Apps/simpler/node_modules/@uploadcare/react-widget/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

**Comment by nd0ut** [comment]
Ok, let's go that way. I bootstrapped project via `create-next-app` and  pushed it to the repo, try to clone it and run. Will it work?

https://github.com/nd0ut/temp-next-js-react-widget-test

**Comment by nd0ut** [comment]
Do you have some custom webpack or compiler configs in your project?

**Comment by louisaoge** [comment]
I'm facing the same issue

**Comment by skreutzberger** [comment]
@nd0ut Thank you so much for taking the time to help us with it. Your test project works AND I found the reason why it did not work for me: I had Nextjs 12.1.6 installed. After upgrading to Nextjs 12.2.1 the line 
`import { Widget } from "@uploadcare/react-widget/en-min/index.js"` works fine!

So my old Nextjs was the reason. Thanks again!!!

**Comment by nd0ut** [comment]
Hey @skreutzberger, I finally understood the Next.js error meaning. By `exports in ES module scope` they seem to mean `exports` field in `package.json` not export statement as I thought. I will release another patch version asap. So it would work under `2.1.6` too but you will need to use import without `index.js` - `@uploadcare/react-widget/en-min`

**Comment by skreutzberger** [comment]
awesome, thanks!

**Comment by skreutzberger** [comment]
Thanks a lot for going deeper into the `node_module` "rabbit hole" to even better fix it 🙌
I upgraded to widget `2.1.4` and can confirm that `import @uploadcare/react-widget/en-min` is enough and works well.

**Comment by wub** [comment]
Hey @nd0ut, I'm receiving the same error when using any of the imports, with any version, with [Remix](https://remix.run) v1.8.0.

I had to write a patch like this to get it to compile:
```diff
diff --git a/node_modules/@uploadcare/react-widget/package.json b/node_modules/@uploadcare/react-widget/package.json
index 545a5bc..ec5f068 100644
--- a/node_modules/@uploadcare/react-widget/package.json
+++ b/node_modules/@uploadcare/react-widget/package.json
@@ -2,7 +2,6 @@
   "name": "@uploadcare/react-widget",
   "version": "2.1.3",
   "description": "React component for Uploadcare Widget",
-  "type": "module",
   "main": "dist/cjs/index.js",
   "module": "dist/esm/index.js",
   "types": "types/index.d.ts",
```

Updating to the latest versions didn't seem to help, so for now I'm just using v2.1.3 + patch.

**Comment by nd0ut** [comment]
Hey @wub,

could you try `@uploadcare/react-widget@3.0.0-alpha.0`? It should work even with `@uploadcare/react-widget/en` imports in Remix.

**Comment by maxfi** [comment]
Hi @wub. I'm using `remix@1.11.1` and `@uploadcare/react-widget@3.0.0-alpha.0` and am getting the following ts error:

```tsx
import { Widget } from "@uploadcare/react-widget/en";
//                     ^ Cannot find module '@uploadcare/react-widget/en' or its corresponding type declarations.ts(2307)
```

Any ideas?

Thanks!

**Comment by nd0ut** [comment]
Hey @maxfi, 

Please use `v2.4.1` instead of `v3.0.0-alpha.0`.

And create `react-widget.d.ts` with the following contents:

```
declare module "@uploadcare/react-widget/en" {
  export * from "@uploadcare/react-widget/types/index.ts";
}
```

Then everything should work.

Remix doesn't have good ESM support, especially with typescript. Actually this problem should be solved by setting typescript `moduleResolution` to `node16` or `nodenext`. It requires user package to be ESM (`type: 'module'`) that isn't possible because Remix app running as CJS.

**Comment by nd0ut** [comment]
I have some thoughts about how to fix it on the package layer.
