### ISSUE TITLE
ReferenceError: exports is not defined in ES module scope

### ISSUE THREAD

**Issue by chartgerink** [uploadcare/react-widget#338]
Thanks for the great work on this module - we use it everyday in our product and I much appreciate all the effort that goes in 🙏 

### Describe the bug

After upgrading to the latest version, the widget creates an unrecoverable error. Before upgrading everything seems to work fine.

### Expected behavior

The widget works as before.

### Code / screenshots

```
file:///Users/FOLDER/node_modules/@uploadcare/react-widget/dist/cjs/index.js:3
Object.defineProperty(exports, '__esModule', { value: true });
                      ^

ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/FOLDER/node_modules/@uploadcare/react-widget/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/FOLDER/node_modules/@uploadcare/react-widget/dist/cjs/index.js:3:23
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

### Environment

 - Library version:  2.1.3
 - Language/framework version: BlitzJS 0.45.4
 - OS version: macOS 12.4

Might this be related to the changes in #333?

**Comment by nd0ut** [comment]
Hey @chartgerink,

please try v2.1.4 and tell me if it works for you

**Comment by chartgerink** [comment]
@nd0ut ahh perfect, thank you! 

`dependabot` hadn't upgraded to this one - sorry to hassle you and much appreciated for the *very* rapid response on here!
