### ISSUE TITLE
Metadata support

### ISSUE THREAD

**Issue by karol-unum-la** [uploadcare/react-widget#341]
Hey,

How can I add metadata to file before an upload ?

I would like to use functionality from this release:

https://github.com/uploadcare/uploadcare-widget/releases/tag/v3.18.0

Basically I would like to set metadata for Panel component

**Comment by optlsnd** [comment]
Hey @karol-unum-la, you can use either the `metadata` or `metadataCallback` settings object key depending on whether you need to set metadata on widget/dialog/panel initialization or dynamically, right before an upload request. See https://github.com/uploadcare/uploadcare-widget/pull/915#issue-1300853920 for more details. Here's an example of using `metadataCallback` with Panel

```js
const user = {
  name: "John Doe",
  email: "john@acme.com"
};

function setMetadata() {
  return {
    timestamp: Date.now(),
    ...user
  };
}

const panel = uploadcare.openPanel("#panel", null, "", {
  tabs: "file",
  metadataCallback: setMetadata
});
```

[Codesandbox demo](https://codesandbox.io/s/panel-metadatacallback-cv3t6b?file=/app.js:64-319)

**Comment by karol-unum-la** [comment]
thanks 👍  but how to use it with <Panel /> react component ?

**Comment by optlsnd** [comment]
Sorry, I shared the example for `uploadcare-widget`. When using `react-widget`, the approach is similar

```jsx
import { Panel } from "@uploadcare/react-widget";

const App = () => {
  return (
    <Panel
      publicKey="your_public_key"
      metadata={{ foo: "bar" }}
      // or
      metadataCallback={() => {
        return {
          foo: "bar"
        };
      }}
    />
  );
};
```

[Codesanbox demo](https://codesandbox.io/s/react-widget-panel-metadata-nm7hur)

**Comment by karol-unum-la** [comment]
thanks!

**Comment by PlasticLizard** [comment]
Hello - I'm trying to do the same thing, but with the Widget, not the Panel. The metadata and metadata callbacks seems ignored on the Widget, and I can't figure out how to access the right object in the callbacks to set the metadata manually.
