### ISSUE TITLE
Unable to use en-min bundle

### ISSUE THREAD

**Issue by insectman** [uploadcare/react-widget#342]
### Describe the bug

Unable to use english-minified bundle

### Expected behavior

webpack should compile the project without errors

### Code / screenshots

...
import { Widget } from '@uploadcare/react-widget/en-min';
...

leads to the following errors:
ERROR in ./node_modules/@uploadcare/react-widget/en-min/dialog-fabc3b17.js 1:128-184
Module not found: Error: Can't resolve 'uploadcare-widget/uploadcare.lang.en.min' in 'C:\project-path\node_modules\@uploadcare\react-widget\en-min'
ERROR in ./node_modules/@uploadcare/react-widget/en-min/uploader-f2bf0eba.js 1:159-215
Module not found: Error: Can't resolve 'uploadcare-widget/uploadcare.lang.en.min' in 'C:\project-path\node_modules\@uploadcare\react-widget\en-min'

### Environment

@uploadcare/react-widget: 2.1.5
webpack: 5.74.0
Windows 10 Pro

**Comment by nd0ut** [comment]
Hey @insectman,

Please try `@uploadcare/react-widget/en-min/index.js`, will it work for you?. For some reason, your webpack instance doesn't resolve `exports` field. Could you share webpack config?

**Comment by nd0ut** [comment]
Hey @insectman,

Please try `@uploadcare/react-widget@2.1.6-alpha.0` and tell me if it will work for you.

**Comment by insectman** [comment]
> Hey @insectman,
> 
> I guess the problem is the missing extension in the import path on our side. Please try `@uploadcare/react-widget@2.1.6-alpha.0` and tell me if it work for you.

It appears to be working, thanks.
