### ISSUE TITLE
How to clear/reset the widget programmatically?

### ISSUE THREAD

**Issue by kkomelin** [uploadcare/react-widget#346]
### Question

1. I upload an image to a comment. 
2. Then I publish the comment. 
3. The widget still includes the uploaded image.

Could you please advise me on how to do reset the widget?

My context:

```typescript
const widgetApi = useRef<WidgetAPI | null>(null)

<Widget
  ref={widgetApi}
/>
```

Would be nice to have something like:

```typescript
widgetApi.current?.value(null)
// or
widgetApi.current?.reset()
```

**Comment by kkomelin** [comment]
Found [this hack](https://codesandbox.io/s/uploadcarereact-widget-clear-after-upload-6h7vc?file=/src/index.js:153-382):
```typescript
const Example = () => {
  const [key, rerender] = useReducer(v => !v);

  const onChange = images => {
    console.log(images);
    rerender();
  };

  return <Widget key={key} publicKey="demopublickey" onChange={onChange} />;
};
```
but I still think that the component should provide a way to clear itself.

**Comment by kkomelin** [comment]
> Found [this hack](https://codesandbox.io/s/uploadcarereact-widget-clear-after-upload-6h7vc?file=/src/index.js:153-382):
> 
> ```ts
> const Example = () => {
>   const [key, rerender] = useReducer(v => !v);
> 
>   const onChange = images => {
>     console.log(images);
>     rerender();
>   };
> 
>   return <Widget key={key} publicKey="demopublickey" onChange={onChange} />;
> };
> ```
> 
> but I still think that the component should provide a way to clear itself.

It doesn't work.

**Comment by nd0ut** [comment]
Hey @kkomelin,
I'm going to add this API method straight to the `widgetApiRef`.
For now you can use the following workaround:

```js
import uploadcare from 'uploadcare-widget'

const Example = () => {
  const ref = useRef()
  const handleClear = () => {
    const el = ref.current.getInput()
    const widget = uploadcare.Widget(el)
    widget.value(null)
  }
  return (
    <>
      <button onClick={handleClear}>Clear</button>

      <Widget
        ref={ref}
        publicKey='demopublickey'
      />
    </>
  )
}
```

**Comment by kkomelin** [comment]
Thanks you so much @nd0ut !
