### ISSUE TITLE
Widget upload bug: jQuery.Deferred exception: e is not a function

### ISSUE THREAD

**Issue by heymartinadams** [uploadcare/react-widget#351]
## Description

Upon uploading an image from the desktop, I get the following issue:
`jQuery.Deferred exception: e is not a function`

### Steps to reproduce

1. Sign up at [simplerlist.com](https://simplerlist.com)
2. Fill out your name, then try to upload a profile photo.
3. After upload, I get a blank screen: 
<img width="1276" alt="CleanShot 2022-10-18 at 10 18 44@2x" src="https://user-images.githubusercontent.com/11673745/196500987-f7f6bb2c-8fde-4de5-89b2-6e1cf2f25a94.png">
4. The console says this: 
<img width="1017" alt="CleanShot 2022-10-18 at 10 17 55@2x" src="https://user-images.githubusercontent.com/11673745/196501028-d6304988-44b6-4fef-9b56-8e927036e034.png">

### Environment

- widget version: `"@uploadcare/react-widget": "^2.2.0",`
- `node -v`: `v16.16.0`

**Comment by heymartinadams** [comment]
For what it’s worth, I’m using `next-safe` to limit API calls to third-party libraries. Not sure if that breaks Uploadcare.

**Comment by nd0ut** [comment]
Hey @heymartinadams,

`next-safe` is definitely not a problem.

Looks like there are some naming collisions on js minification stage. 

Are you using the default next.js webpack config or the custom one?

**Comment by nd0ut** [comment]
Is it Next.js v12.3.0?

Anyway, please try to disable `swcMinify` so Next.js will use terser in that case. I'm pretty sure that SWC minifier causes this problem. 

I will prepare an issue to next.js If it helps.

**Comment by heymartinadams** [comment]
Thanks so much, @nd0ut! That was the issue indeed ☺️

**Comment by KrokoYR** [comment]
Hi @nd0ut can you please share a link to an issue to NextJS please, I've met the same problem, so I would like to subscribe to updates.

**Comment by heymartinadams** [comment]
`NextJS 13` now has `swcMinify` enabled by default. https://nextjs.org/docs/advanced-features/compiler

Any update on when we can use it, @nd0ut?

**Comment by nd0ut** [comment]
@KrokoYR @heymartinadams 

Sorry guys, I haven't created an issue to next.js repo yet.
Writing a minimal reproducible example was harder than I thought.

**Comment by nd0ut** [comment]
Here it is - https://github.com/swc-project/swc/issues/6463

**Comment by nd0ut** [comment]
This problem was fixed in `next@13.0.5`
