### ISSUE TITLE
Is there a non-jQuery bundle for uploadcare/react-widget?

### ISSUE THREAD

**Issue by davidalejandroaguilar** [uploadcare/react-widget#352]
Is there a non-jQuery bundle for uploadcare/react-widget? 

I'm using `"@uploadcare/react-widget": "^2.2.0"` and importing it like `import { Widget } from '@uploadcare/react-widget/en-min';`.

**Comment by nd0ut** [comment]
Hey @davidalejandroaguilar,

do you mean that you already have jQuery instance on the page?

**Comment by davidalejandroaguilar** [comment]
Thanks for the time taken to answer @nd0ut , I was actually looking for a bundle that didn't have `jQuery` as a dependency. Wanted to have a smaller bundle size.

Closing this now, thanks again.
