### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by jeetiss** [uploadcare/react-widget#49]
Provide typescript type definitions, include it in this package

**Comment by LXSMNSYC** [comment]
Any changes that this would get implemented?

**Comment by jeetiss** [comment]
Hello

I can't implement this because I've never worked with TS before, but I agree that definitions would improve developer experience and we could add an `index.d.ts` file to the package with type declarations.

I'm going to add a "Help Needed" tag to this issue, so if someone wants to contribute this might be a good place to start.

**Comment by LXSMNSYC** [comment]
As we needed the type definitions, maybe I can try looking up the codebase for the type definitions this weekend

**Comment by bautrukevich** [comment]
Working on it at https://github.com/uploadcare/react-widget/pull/55

**Comment by bautrukevich** [comment]
I think, that we can close the issue, @jeetiss? : )

**Comment by jeetiss** [comment]
I will close it after publish

**Comment by jeetiss** [comment]
released in 1.1.0
