### ISSUE TITLE
Please reconsider shipping untranspiled code

### ISSUE THREAD

**Issue by GriffinSauce** [uploadcare/react-widget#50]
Hi, we recently upgraded from the regular script to this widget, this is my experience:

I just spent a couple hours debugging why we're suddenly getting errors in older browsers, finding that this module is not ES5 and subsequently faffing around with webpack to get it all to work nicely.

From your readme:
> **Note**, this library comes untranspiled. It means that if you want to support
IE11, make sure you transpile `node_modules`. [Learn more][es6-debate]

First off: this note is not emphasised enough. Untranspiled code is a silent failure in the build process, a lot of devs will only find it when it hits a user or a test.

Secondly: that learn more link states the following:

> The priority is to ensure that people can consume code with the least amount of faffery. 

If that is the goal, this strategy is failing you (and me).

Edit: sorry about the snarkyness of the above. I just hope you'll reconsider or at least put a way more obvious warning in the readme.

**Comment by jeetiss** [comment]
No faffery!!!

@GriffinSauce thank you for guiding me on the right way.
I will release the version of react-widget with transpiled code soon.

**Comment by GriffinSauce** [comment]
Just realised I never thanked you for this, but thanks for the quick response and action! Awesome :)
