### ISSUE TITLE
Type definitions not included in the installed package.

### ISSUE THREAD

**Issue by LXSMNSYC** [uploadcare/react-widget#59]
Updated my `@uploadcare/react-widget` and it still throws the TypeScript error. Confused, I checked the node_modules to see the installed package, and found out that the type definitions are not included.

<img width="219" alt="Screen Shot 2019-11-21 at 2 42 47 PM" src="https://user-images.githubusercontent.com/4783372/69313668-32b65480-0c6d-11ea-96fd-6ab2106bef67.png">

**Comment by bautrukevich** [comment]
Oh, sorry. It seems we forget to include to publishing package.

**Comment by jeetiss** [comment]
It should be patch release, but `release-it` didn't think so we have 1.2.0

**Comment by jeetiss** [comment]
@LXSMNSYC  I'm testing types and now it's here 🙌🏻
<img width="329" alt="Снимок экрана 2019-11-21 в 14 40 43" src="https://user-images.githubusercontent.com/6726016/69335317-b708d780-0c6d-11ea-8c45-e9fed526616d.png">

**Comment by LXSMNSYC** [comment]
I tested this yesterday and it is working properly now, thanks!
