### ISSUE TITLE
Using EffectsTab causes TypeScript error

### ISSUE THREAD

**Issue by optlsnd** [uploadcare/react-widget#62]
I use TypeScript and I get the error:
`'effects' does not exist on type 'IntrinsicAttributes & WidgetProps & { children?: ReactNode; }`

I have looked in the repository and I can not find effects either in types declarations.

https://github.com/uploadcare/react-widget/blob/master/types/index.d.ts

**Comment by jeetiss** [comment]
fixed in 1.2.1
